#! /bin/bash

# resources #################################

#PBS -N run_deviceQuery
#PBS -l nodes=gpu12:ppn=1:gpus=1:default,walltime=1:00:00
#PBS -t 1-4

module load cuda-10.1
input=`head -n $PBS_ARRAYID $SINGULARITY_HOME/list_data_deviceQuery.log | tail -1`

echo "==========================================================================="
sleep 3m
echo "input: $input"
cat $PBS_GPUFILE
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
/home/jjlee/Local/bin/deviceQuery
nvidia-smi
